
require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '9.0'

target 'mobile' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])


end

target 'mobile-tvOS' do
  # Pods for mobile-tvOS

  target 'mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
